version: '3.7'

volumes:
  pytest_ratl.egg-info:

services:
  pytest-ratl:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/pytest-ratl
      - pytest_ratl.egg-info:/usr/src/pytest-ratl/pytest_ratl.egg-info
    environment:
      PYTHONBREAKPOINT: ipdb.set_trace
